[project]
name = "hemoflow"
version = "0.1.0"
description = "Visualize velocity image series from a phase contrast magnetic resonance imaging study as three-dimensional vector field."
readme = "readme.md"
requires-python = ">=3.12"
dependencies = ["pydicom>=3.0.1", "streamlit>=1.41.1"]

[dependency-groups]
dev = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.5.49",
]
