[book]
title = "Hemoflow Documentation"
description = "Visualize velocity image series from a phase contrast magnetic resonance study as a three-dimensional vector field."
authors = ["Lewin Town"]
language = "en"

